# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ruby_outbox_gem.gemspec
gemspec

group :development, :test do
  gem "rspec", "~> 3.0"
  gem "rubocop", "~> 1.21"

  gem "sqlite3", "~> 1.7"
  gem "pry"
end

gem "irb"
gem "rake", "~> 13.0"